### ISSUE TITLE
Add to Library

### ISSUE THREAD

**Issue by moneymaker365** [moneymaker365/plugin.video.ustvvod#18]
wishes from the users:

Would it be possible to create an "Add to Library" feature, like the Hulu plugin, with the ability to scrape all favorited shows and package them as .strm files to go in your library (of course, kinks preventing certain shows from being added to favorites would have to be resolved, too).

**Comment by alexdunlop81** [comment]
Will require some refactoring but should be possible.

**Comment by slices81** [comment]
Mostly done,  still needs a script add-on to automate.
