### ISSUE TITLE
Nick

### ISSUE THREAD

**Issue by mspencer92** [moneymaker365/plugin.video.ustvvod#38]
The latest viacom update that was applied broke Nickelodeon playback. Here is my log.
https://gist.github.com/mspencer92/50c36d42a8a166d3e0d2

**Comment by alexdunlop81** [comment]
Cookie handling had been changed in this area is there still an issue

**Comment by z-e-r-o** [comment]
There was further improvement in handling the request of getting streams.
Also the proxy part was improved.
Are there still problems?
If there is no reply within 1 week I will close the issue.

**Comment by mspencer92** [comment]
Sorry for no replies from me. I tried mutltiple show/episodes I no longer get this error and things are playing fine. Thanks
