### ISSUE TITLE
None of the channels work

### ISSUE THREAD

**Issue by 26psicivic** [moneymaker365/plugin.video.ustvvod#41]
If I click ABC it takes me to all the ABC shows.
Then I click on a show and it takes me to the next screen, Episodes and Clips.
Now here's where it messes up.
When I click on Episodes, Clips, Previews, etc. it gives me a script failed error.
In the log it says this:
module' object has no attribute 'SORT_METHOD_DATEADDED'

**Comment by alexdunlop81** [comment]
Issue with Frodo and last release. Either upgrade or this latest from github.
