### ISSUE TITLE
Unable to open any channel, even after deleting .kodi/userdata/addon_data/plugin.video.ustvvod

### ISSUE THREAD

**Issue by xtson** [moneymaker365/plugin.video.ustvvod#45]
Just installed the .zip from the git repo. Full log:

```
13:48:25 T:1727321152  NOTICE: Thread LanguageInvoker start, auto delete: false
13:48:26 T:1727321152  NOTICE: -->Python Interpreter Initialized<--
13:48:32 T:1727321152  NOTICE:


                                             start of USTV VoD plugin
13:48:32 T:1727321152  NOTICE: !!! plugin loading of site : comedy
13:48:32 T:1727321152  NOTICE: ************************************* INT **********************************
13:48:32 T:1727321152  NOTICE: connection :: getURL :: url = http://www.cc.com/shows
13:48:32 T:1727321152   ERROR: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.ustvvod-master/addon.py): failed to run the gc to clean up after running prior to shutting down the Interpreter
13:48:32 T:1727321152 WARNING: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.ustvvod-master/addon.py): the python script "/storage/.kodi/addons/plugin.video.ustvvod-master/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
13:48:32 T:1968697344   ERROR: GetDirectory - Error getting plugin://plugin.video.ustvvod/?fanart=%22%2fstorage%2f.kodi%2faddons%2fplugin.video.ustvvod-master%2ffanart.jpg%22&mode=%22comedy%22&name=%22Comedy%20Central%22&sitemode=%22rootlist%22&thumb=%22%2fstorage%2f.kodi%2faddons%2fplugin.video.ustvvod-master%2fresources%2fimages%2fcomedy.png%22&url=%22%22
13:48:32 T:1968697344   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ustvvod/?fanart=%22%2fstorage%2f.kodi%2faddons%2fplugin.video.ustvvod-master%2ffanart.jpg%22&mode=%22comedy%22&name=%22Comedy%20Central%22&sitemode=%22rootlist%22&thumb=%22%2fstorage%2f.kodi%2faddons%2fplugin.video.ustvvod-master%2fresources%2fimages%2fcomedy.png%22&url=%22%22) failed
13:48:33 T:1727321152  NOTICE: Thread BackgroundLoader start, auto delete: false
```

**Comment by terminalmage** [comment]
Confirmed same issue with USTV VoD 1.2.0 on Kodi 14.1.

**Comment by terminalmage** [comment]
I'm able to access CBS, so it's not a global problem. Happened several days after 1.2.0 was released, too, so it's likely just scrapers needing an update. Right now I can't open Comedy Central nor MSNBC, and The CW will get as far as an episode list but none of the episodes will play.

**Comment by slices81** [comment]
For thecw set preferred stream type to RTMP, MSNBC there is a known issue with playlists but shows should work. I'm reworking some things in the background at the moment so will be clearer when I merge the code.

**Comment by terminalmage** [comment]
@slices81 for MSNBC, it looks like they moved the feed information into a ``<script>`` tag (current code looks for a div), look for the text "jQuery.extend".

**Comment by slices81** [comment]
Thanks, I actually have this fixed but in a version that is dependant on me finishing some other changes, will be there soon.

**Comment by terminalmage** [comment]
Great, thanks for the update. I hacked together something with html.parser and urllib that is clunky but will work in the interim.

**Comment by slices81** [comment]
Try the latest from github.

**Comment by terminalmage** [comment]
You sure? I still see the latest from the ``master`` branch looking for a ``div`` tag: https://github.com/moneymaker365/plugin.video.ustvvod/blob/master/resources/lib/stations/msnbc.py#L49

**Comment by slices81** [comment]
Yes in the except block because this still applies to some shows, most use the jquery hence the regex to get the json.

**Comment by terminalmage** [comment]
Derp, I didn't even notice the new code with the regex.

Installing from develop works, thanks.

Incidentally, is there a good way of replacing a plugin directory in ``~/.kodi/addons`` while Kodi is running? I backed up the existing directory, and then cloned the git repo right there in ``~/.kodi/addons``, but I kept getting "script failed" until I restarted Kodi.

**Comment by xtson** [comment]
Still happens with a few channels, not all though.

This is the important error, nothing to do with RTMP:

> 13:48:32 T:1968697344   ERROR: GetDirectory - Error getting plugin://plugin.video.ustvvod/?fanart=%22%2fstorage%2f.kodi%2faddons%2fplugin.video.ustvvod-master%2ffanart.jpg%22&mode=%22comedy%22&name=%22Comedy%20Central%22&sitemode=%22rootlist%22&thumb=%22%2fstorage%2f.kodi%2faddons%2fplugin.video.ustvvod-master%2fresources%2fimages%2fcomedy.png%22&url=%22%22

When this happens it doesn't even show the channel's show list, it merely stays in the network list.

**Comment by slices81** [comment]
Confusing multiple issues here. MSNBC site change issue now fixed. There was a issue with thecw hls playback now fixed.

There is a known issue with viacomm sites on some environments.

**Comment by z-e-r-o** [comment]
Why does the thumb is pointing to <plugin-name>-master.
There is no such folder.

**Comment by z-e-r-o** [comment]
Look at this line:

fanart=%22%2fstorage%2f.kodi%2faddons%2fplugin.video.ustvvod-master%2ffanart.jpg

Please check the name of the plugin in the addon folder.

**Comment by slices81** [comment]
Because it's been installed from github, try uninstalling and installing from the repo, although depending on your os/kodi version you may still have issues with comedy.
