### ISSUE TITLE
UsTv Now vs UsTv Vod

### ISSUE THREAD

**Issue by faerysdust** [moneymaker365/plugin.video.ustvvod#46]
I'm pretty new to this, I was wondering if Us Tv Now and Us Tv VOD is the same thing and if so do I need to have both addon's installed? Also for Us Tv VOD when I try to open it I get Script Error, any solutions to a fix? I'm using amazon fire tv and spmc version, I've tried it on gothem v13.2 and on helix v14.1 and still get the same error, I've tried deleting and reinstalling everything and still it errors. On Us Tv Now when i go to add the add on via system-addons-install from zip-*******-add ons- ustv now i get dependencies not met, but when i go to video add ons and add it i can but then i go to open it and choose a channel either nothing happens or i get a playback failed error check logs which i have done and can't find anything. i have signed up for an account with them and put in the user and pw, uninstalled/reinstalled, forced refresh and still nothing works any solutions for a fix on this as well?

**Comment by slices81** [comment]
They are different, for ustvvod what is your connection set to, known issue with DNS. Also try the latest from github failing that, post a log.

**Comment by faerysdust** [comment]
direct
