### ISSUE TITLE
Dependencies not met

### ISSUE THREAD

**Issue by watermouf** [moneymaker365/plugin.video.ustvvod#47]
I am running 14.2 on Windows as well as a fireTV stick, both boxes told me today that USTVVOD has dependencies that are not met. I chose not to disable the addon and it does still seem to work, but installing on a new box it gives "Dependicnes not met msg"

**Comment by z-e-r-o** [comment]
Is it still keeping the messages with the current version?
If yes post a log file.
Information how to you will find here: http://kodi.wiki/view/Log_file

**Comment by ReactorShop** [comment]
I just installed it in an Apple TV 2 box right after it was jailbroken with a tethered iOS 6.2.1 image using Seas0nPass, nothing else is installed, and I get the Dependencies not met message.

Here's the log:

https://pastebin.com/5EYR5ZKH
