### ISSUE TITLE
empty shows

### ISSUE THREAD

**Issue by dtrigleth** [moneymaker365/plugin.video.ustvvod#48]
I began seeing empty shows last week.  I'm honestly not sure the exact date, but my system upstairs still showed episodes populating within shows, whereas my system in the basement did not.  I realized today that my system upstairs was version 1.2.4 and the basement was 1.2.5c.  I rolled my basement system back to 1.1.9 (the most recent available for some reason), and episodes showed back up.  Any idea why some shows would show up as empty (zero episodes or segments available)?

**Comment by slices81** [comment]
Try the latest from github, another user reported a similar issue that is now now fixed.
