### ISSUE TITLE
network cache issue and America's Got Talent won't play

### ISSUE THREAD

**Issue by dtrigleth** [moneymaker365/plugin.video.ustvvod#49]
Here is my log.

https://gist.github.com/dtrigleth/8aa71c8a34c5b0ba7dd4#file-debug-log

Debug begins on line 333 with first the issue of AGT not opening on line 549 and 707 (I try opening the current episode a few times every time), and then the issue of NBC taking forever to open is shown beginning on line 999 (timestamp of 20:36 - you see on line 1012 timestamp 20:39 that my screensaver was activated, and then finally NBC loaded on line 1020 timestamp 20:42, so a total of about 6 minutes).  While I was in NBC, I tried playing AGT a couple more times, then I exit out and access NBC again on line 1396 (time 20:44) and it finally loads on line 1412 (time 20:49, total wait of 5 minutes).  For kicks I tried playing AGT again, with still no luck.

**Comment by slices81** [comment]
Is this still happening in the latest version? Can't reproduce.

**Comment by dtrigleth** [comment]
Away on work.  Will check when I get home tonight and if still happening I'll post a new log.

**Comment by dtrigleth** [comment]
Sorry it took so long, but this issue was resolved as soon as I upgraded to Kodi.
