### ISSUE TITLE
Missing Shows

### ISSUE THREAD

**Issue by dtrigleth** [moneymaker365/plugin.video.ustvvod#59]
I just set up a new Raspberry Pi 2 with the newest OpenELEC and installed the USTV VoD add-o,.  However, some shows are missing, for example Bones from the FOX network. It is still accessible via my RPi1 B+, also running OpenELEC. Looking deeper, there are quite a few shows missing and refreshing the TV database has not resolved any of them.

**Comment by slices81** [comment]
Can't understand what is happening here, upload a log?

**Comment by dtrigleth** [comment]
It must have been something up with the network sites not being read correctly. It has since been resolved. Sorry for not closing the issue sooner.
