### ISSUE TITLE
USTV Favorites - where?

### ISSUE THREAD

**Issue by dtrigleth** [moneymaker365/plugin.video.ustvvod#62]
I would like to migrate my USTV favorites from one system to another, but I can't seem to find where or how the favorites are saved.  Is there a database or XML file?  Is there a process to migrating data from one install of USTV VoD to another?

**Comment by slices81** [comment]
There is another addon called script.module.free.cable.database which is where they live.

**Comment by dtrigleth** [comment]
I did find script.module.free.cable.database in the .kodi/addons folder, but within the free.cable lib folder, I only see shows.db which appears to be an exhaustive list of every show that has been cached.  Is there a specific area of that file that the favorites are saved to, or is it a tag on shows?  Does that whole shows.db simply need to be copied from one system to another?

**Comment by slices81** [comment]
It's a collun on the show table, copy the entire file.

**Comment by dtrigleth** [comment]
So no possibility of merging two? Can this file be edited in any program?

**Comment by slices81** [comment]
It's a sqllite dB so am sqllite editor should work

**Comment by dtrigleth** [comment]
Thank you very much.
