### ISSUE TITLE
CBS provider content broken

### ISSUE THREAD

**Issue by WhereRtheInterwebs** [moneymaker365/plugin.video.ustvvod#64]
When logged into CBS all access from the USTV VOD settings page, all CBS videos fail to play.  When logged out videos play correctly.  
For me, this started 1/27/16.

Kodi 14.2 on Ubuntu 12.04.5 and Kodi 15 on Windows 10 both using USTV VOD version 1.3.8 are affected with the same information in the log.  

Log:
`                                             start of USTV VoD plugin
14:59:50 T:140358152697600  NOTICE: !!! plugin loading of site : cbs
14:59:50 T:140358152697600  NOTICE: connection :: getURL :: url = https://www.cbs.com/account/login/
14:59:51 T:140358152697600   ERROR: CPythonInvoker(25, /home/****/.kodi/addons/plugin.video.ustvvod-master/addon.py): failed to run the gc to clean up after run to shutting down the Interpreter
14:59:51 T:140358152697600 WARNING: CPythonInvoker(25, /home/****/.kodi/addons/plugin.video.ustvvod-master/addon.py): the python script "/home/****/.kodi/addons/plugin.video.ustvvod-master/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
14:59:51 T:140358758344576   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ustvvod/?url="http%3A%2F%2Fwww.cbs.com%2Fshows%2Fsupergirl%2Fvideo%2FWlNyPr941b2jS6Pi0W4uMzrewHWmZ1Bn%2Fsupergirl-strange-visitor-from-another-planet%2F"&mode="cbs"&sitemode="play_video"]
14:59:51 T:140358152697600  NOTICE: Thread BackgroundLoader start, auto delete:false`

**Comment by faerysdust** [comment]
I am having the same problem started on 1-26-16, I have uninstalled and reinstalled addon, I have signed out and it still dont play, I am using kodi- isengard 15.2- on amazon firetv top box

**Comment by faerysdust** [comment]
My log looks pretty much like the one above and I have version 1.3.8 as well sorry forgot to add this in previous comment

**Comment by slices81** [comment]
Ok I understand the issues here.
1)Addon falls over on invalid login, fix now in git hub.
2)It will show you locked content even if your account isn't valid.
3)Login is now per video and requires a token to by passed.
4)It's not clear to some people where to enter login details.

Working on the third issue at the moment.

**Comment by slices81** [comment]
Fix in github

**Comment by WhereRtheInterwebs** [comment]
It works!  Thank you
The video is coming in at 480p.  Is there still a missing piece of the puzzle?
