### ISSUE TITLE
cbs is broke

### ISSUE THREAD

**Issue by two-dogs** [moneymaker365/plugin.video.ustvvod#67]
my spouse :) lives for two shows, both on cbs, i looked at the logs, i dont think it is my end, i tested on two diff platforms, linux ubuntu14.04 and osuse-tw, kodi is the lastest snapshot and also latest addon update

https://gist.github.com/anonymous/b6c7106bab0b961fe017

**Comment by GoodOmens83** [comment]
Having the same issue.

I see the following in my logs:
                                                                                                                                                                           
`15:03:49  80.095383 T:139650677843712   ERROR: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.ustvvod/addon.py): failed to run the gc to clean up after running prior to shutting down the Interpreter                                                
15:03:49  80.095451 T:139650677843712 WARNING: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.ustvvod/addon.py): the python script "/storage/.kodi/addons/plugin.video.ustvvod/addon.py" has left several classes in memory that we couldn't clean up.
15:03:49  80.105515 T:139652097779776   ERROR: GetDirectory - Error getting plugin://plugin.video.ustvvod/?fanart=%22%2Fstorage%2F.kodi%2Faddons%2Fplugin.video.ustvvod%2Ffanart.jpg%22&mode=%22cbs%22&name=%22CBS%22&sitemode=%22rootlist%22&thumb=%22%2Fsto
15:03:49  80.106812 T:139652097779776   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ustvvod/?fanart=%22%2Fstorage%2F.kodi%2Faddons%2Fplugin.video.ustvvod%2Ffanart.jpg%22&mode=%22cbs%22&name=%22CBS%22&sitemode=%22rootlist%22&thumb=%22%2Fst
15:04:22 113.119980 T:139652097779776  NOTICE: NFS is idle. Closing the remaining connections.                                                                                                                                                               
15:04:45 136.312012 T:139650677843712   ERROR: CPythonInvoker(18, /storage/.kodi/addons/plugin.video.ustvvod/addon.py): failed to run the gc to clean up after running prior to shutting down the Interpreter                                                
15:04:45 136.312134 T:139650677843712 WARNING: CPythonInvoker(18, /storage/.kodi/addons/plugin.video.ustvvod/addon.py): the python script "/storage/.kodi/addons/plugin.video.ustvvod/addon.py" has left several classes in memory that we couldn't clean up.
15:04:45 136.319901 T:139652097779776   ERROR: GetDirectory - Error getting plugin://plugin.video.ustvvod/?fanart=%22%2Fstorage%2F.kodi%2Faddons%2Fplugin.video.ustvvod%2Ffanart.jpg%22&mode=%22cbs%22&name=%22CBS%22&sitemode=%22rootlist%22&thumb=%22%2Fsto
15:04:45 136.321121 T:139652097779776   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ustvvod/?fanart=%22%2Fstorage%2F.kodi%2Faddons%2Fplugin.video.ustvvod%2Ffanart.jpg%22&mode=%22cbs%22&name=%22CBS%22&sitemode=%22rootlist%22&thumb=%22%2Fst
15:05:01 152.594528 T:139652097779776   ERROR: Control 8200 in window 10000 has been asked to focus, but it can't  `

**Comment by slices81** [comment]
Fix in github now.

**Comment by two-dogs** [comment]
I can confirm, CBS is working again, my wife the soaps watcher thanks you very much.
