### ISSUE TITLE
Unable to load CBS list

### ISSUE THREAD

**Issue by WhereRtheInterwebs** [moneymaker365/plugin.video.ustvvod#70]
I am unable to load the list of CBS shows.  They still play from the favorites list.  Log below.  

`start of USTV VoD plugin
21:14:36 T:140268661597952  NOTICE: !!! plugin loading of site : cbs
21:14:36 T:140268661597952  NOTICE: connection :: getURL :: url = http://www.cbs.com/carousels/showsByCategory/0/offset/0/limit/100
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: Exception
21:14:37 T:140268661597952  NOTICE: 'show_id'
21:14:37 T:140268661597952  NOTICE: connection :: getURL :: url = http://www.cbs.com/carousels/showsByCategory/4/offset/0/limit/100
21:14:37 T:140268661597952  NOTICE: Exception with
21:14:37 T:140268661597952  NOTICE: http://www.cbs.com/carousels/showsByCategory/4/offset/0/limit/100
21:14:37 T:140268661597952  NOTICE: connection :: getURL :: url = http://www.cbs.com/carousels/showsByCategory/6/offset/0/limit/100
21:14:38 T:140268661597952  NOTICE: Exception with
21:14:38 T:140268661597952  NOTICE: http://www.cbs.com/carousels/showsByCategory/6/offset/0/limit/100
21:14:38 T:140268661597952  NOTICE: connection :: getURL :: url = http://www.cbs.com
21:14:44 T:140268661597952   ERROR: CPythonInvoker(127, /home/mark/.kodi/addons/plugin.video.ustvvod/addon.py): failed to run the gc to clean up after running prior to shutting down the Interpreter
21:14:44 T:140268661597952 WARNING: CPythonInvoker(127, /home/mark/.kodi/addons/plugin.video.ustvvod/addon.py): the python script "/home/mark/.kodi/addons/plugin.video.ustvvod/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
21:14:44 T:140269368850368   ERROR: GetDirectory - Error getting plugin://plugin.video.ustvvod/?fanart=%22%2fhome%2fmark%2f.kodi%2faddons%2fplugin.video.ustvvod%2ffanart.jpg%22&mode=%22cbs%22&name=%22CBS%22&sitemode=%22rootlist%22&thumb=%22%2fhome%2fmark%2f.kodi%2faddons%2fplugin.video.ustvvod%2fresources%2fimages%2fcbs.png%22&url=%22%22
21:14:44 T:140269368850368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ustvvod/?fanart=%22%2fhome%2fmark%2f.kodi%2faddons%2fplugin.video.ustvvod%2ffanart.jpg%22&mode=%22cbs%22&name=%22CBS%22&sitemode=%22rootlist%22&thumb=%22%2fhome%2fmark%2f.kodi%2faddons%2fplugin.video.ustvvod%2fresources%2fimages%2fcbs.png%22&url=%22%22) failed
21:14:44 T:140268661597952  NOTICE: Thread BackgroundLoader start, auto delete: false
21:15:36 T:140267441051392  NOTICE: ES: Client  from 192.168.1.200 timed out
21:16:14 T:140267416078080  NOTICE: Thread JobWorker start, auto delete: true`

**Comment by rattboi** [comment]
Any reason this isn't merged yet?

**Comment by compuw22c** [comment]
Same, please merge. Hopefully this project isn't abandoned...
